
package dllimports

var dllImportDefs = []importTable{
    /*0*/ {"_Py_NoneStruct", 0},
    /*1*/ {"Py_Initialize", 0},
    /*2*/ {"Py_InitializeEx", 0},
    /*3*/ {"Py_IsInitialized", 0},
    /*4*/ {"Py_Finalize", 0},
    /*5*/ {"Py_FinalizeEx", 0},
    /*6*/ {"Py_EncodeLocale", 0},
    /*7*/ {"Py_DecodeLocale", 0},
    /*8*/ {"PyMem_Free", 0},
    /*9*/ {"PyMem_RawFree", 0},
    /*10*/ {"Py_SetProgramName", 0},
    /*11*/ {"Py_GetProgramName", 0},
    /*12*/ {"PyEval_ThreadsInitialized", 0},
    /*13*/ {"Py_Main", 0},
    /*14*/ {"Py_BytesMain", 0},
    /*15*/ {"PyRun_AnyFile", 0},
    /*16*/ {"PyRun_SimpleFile", 0},
    /*17*/ {"PyRun_SimpleString", 0},
    /*18*/ {"Py_SetPath", 0},
    /*19*/ {"Py_SetPythonHome", 0},
    /*20*/ {"_Py_fopen_obj", 0},
    /*21*/ {"PyImport_AppendInittab", 0},
    /*22*/ {"Py_IncRef", 0},
    /*23*/ {"Py_DecRef", 0},
    /*24*/ {"PyUnicode_AsUTF8", 0},
    /*25*/ {"PyUnicode_DecodeFSDefault", 0},
    /*26*/ {"PyUnicode_FromString", 0},
    /*27*/ {"PyUnicode_GetLength", 0},
    /*28*/ {"PyObject_Str", 0},
    /*29*/ {"PyObject_GetAttr", 0},
    /*30*/ {"PyObject_Call", 0},
    /*31*/ {"PyObject_CallObject", 0},
    /*32*/ {"PyObject_CallNoArgs", 0},
    /*33*/ {"PyObject_Type", 0},
    /*34*/ {"PyObject_HasAttrString", 0},
    /*35*/ {"PyObject_GetAttrString", 0},
    /*36*/ {"PyObject_SetAttrString", 0},
    /*37*/ {"PyObject_DelAttrString", 0},
    /*38*/ {"PyLong_AsDouble", 0},
    /*39*/ {"PyLong_AsLong", 0},
    /*40*/ {"PyLong_AsLongLong", 0},
    /*41*/ {"PyLong_FromDouble", 0},
    /*42*/ {"PyLong_FromLong", 0},
    /*43*/ {"PyLong_FromLongLong", 0},
    /*44*/ {"PyLong_FromString", 0},
    /*45*/ {"PyModule_Create2", 0},
    /*46*/ {"PyImport_Import", 0},
    /*47*/ {"PyModule_GetName", 0},
    /*48*/ {"PyModule_GetDict", 0},
    /*49*/ {"PyModule_AddFunctions", 0},
    /*50*/ {"PyModule_AddIntConstant", 0},
    /*51*/ {"PyModule_AddStringConstant", 0},
    /*52*/ {"PyModule_AddObject", 0},
    /*53*/ {"PyModule_AddObjectRef", 0},
    /*54*/ {"PyDict_SetItem", 0},
    /*55*/ {"PyDict_SetItemString", 0},
    /*56*/ {"PyDict_New", 0},
    /*57*/ {"PyDict_Size", 0},
    /*58*/ {"PyDict_Clear", 0},
    /*59*/ {"PyDict_GetItem", 0},
    /*60*/ {"PyDict_Keys", 0},
    /*61*/ {"PyDict_GetItemString", 0},
    /*62*/ {"PyDict_DelItem", 0},
    /*63*/ {"PyDict_DelItemString", 0},
    /*64*/ {"PyEval_GetBuiltins", 0},
    /*65*/ {"PyEval_GetLocals", 0},
    /*66*/ {"PyEval_GetGlobals", 0},
    /*67*/ {"PyEval_GetFrame", 0},
    /*68*/ {"PyFrame_GetBack", 0},
    /*69*/ {"PyFrame_GetCode", 0},
    /*70*/ {"PyTuple_Size", 0},
    /*71*/ {"PyTuple_GetItem", 0},
    /*72*/ {"PyTuple_SetItem", 0},
    /*73*/ {"PyTuple_GetSlice", 0},
    /*74*/ {"PyTuple_Check", 0},
    /*75*/ {"PyTuple_New", 0},
    /*76*/ {"PyBytes_FromString", 0},
    /*77*/ {"PyObject_CallFunctionObjArgs", 0},
    /*78*/ {"PyType_Type", 0},
    /*79*/ {"_PyType_Name", 0},
    /*80*/ {"PyType_GetModule", 0},
    /*81*/ {"PyList_New", 0},
    /*82*/ {"PyList_SetItem", 0},
    /*83*/ {"PyList_GetItem", 0},
    /*84*/ {"PyList_GetSlice", 0},
    /*85*/ {"PyList_Size", 0},
    /*86*/ {"PyList_Insert", 0},
    /*87*/ {"PyList_Append", 0},
    /*88*/ {"PyBool_FromLong", 0},
    /*89*/ {"PyExc_Exception", 0},
    /*90*/ {"PyExc_ValueError", 0},
    /*91*/ {"PyErr_SetString", 0},
    /*92*/ {"PyErr_NewException", 0},
    /*93*/ {"PyInstanceMethod_New", 0},
    /*94*/ {"PyCFunction_New", 0},
    /*95*/ {"PyObject_Length", 0},
    /*96*/ {"Py_GetPath", 0},
    /*97*/ {"Py_GetPythonHome", 0},
}
const (
    _Py_NoneStruct = 0
    Py_Initialize = 1
    Py_InitializeEx = 2
    Py_IsInitialized = 3
    Py_Finalize = 4
    Py_FinalizeEx = 5
    Py_EncodeLocale = 6
    Py_DecodeLocale = 7
    PyMem_Free = 8
    PyMem_RawFree = 9
    Py_SetProgramName = 10
    Py_GetProgramName = 11
    PyEval_ThreadsInitialized = 12
    Py_Main = 13
    Py_BytesMain = 14
    PyRun_AnyFile = 15
    PyRun_SimpleFile = 16
    PyRun_SimpleString = 17
    Py_SetPath = 18
    Py_SetPythonHome = 19
    _Py_fopen_obj = 20
    PyImport_AppendInittab = 21
    Py_IncRef = 22
    Py_DecRef = 23
    PyUnicode_AsUTF8 = 24
    PyUnicode_DecodeFSDefault = 25
    PyUnicode_FromString = 26
    PyUnicode_GetLength = 27
    PyObject_Str = 28
    PyObject_GetAttr = 29
    PyObject_Call = 30
    PyObject_CallObject = 31
    PyObject_CallNoArgs = 32
    PyObject_Type = 33
    PyObject_HasAttrString = 34
    PyObject_GetAttrString = 35
    PyObject_SetAttrString = 36
    PyObject_DelAttrString = 37
    PyLong_AsDouble = 38
    PyLong_AsLong = 39
    PyLong_AsLongLong = 40
    PyLong_FromDouble = 41
    PyLong_FromLong = 42
    PyLong_FromLongLong = 43
    PyLong_FromString = 44
    PyModule_Create2 = 45
    PyImport_Import = 46
    PyModule_GetName = 47
    PyModule_GetDict = 48
    PyModule_AddFunctions = 49
    PyModule_AddIntConstant = 50
    PyModule_AddStringConstant = 51
    PyModule_AddObject = 52
    PyModule_AddObjectRef = 53
    PyDict_SetItem = 54
    PyDict_SetItemString = 55
    PyDict_New = 56
    PyDict_Size = 57
    PyDict_Clear = 58
    PyDict_GetItem = 59
    PyDict_Keys = 60
    PyDict_GetItemString = 61
    PyDict_DelItem = 62
    PyDict_DelItemString = 63
    PyEval_GetBuiltins = 64
    PyEval_GetLocals = 65
    PyEval_GetGlobals = 66
    PyEval_GetFrame = 67
    PyFrame_GetBack = 68
    PyFrame_GetCode = 69
    PyTuple_Size = 70
    PyTuple_GetItem = 71
    PyTuple_SetItem = 72
    PyTuple_GetSlice = 73
    PyTuple_Check = 74
    PyTuple_New = 75
    PyBytes_FromString = 76
    PyObject_CallFunctionObjArgs = 77
    PyType_Type = 78
    _PyType_Name = 79
    PyType_GetModule = 80
    PyList_New = 81
    PyList_SetItem = 82
    PyList_GetItem = 83
    PyList_GetSlice = 84
    PyList_Size = 85
    PyList_Insert = 86
    PyList_Append = 87
    PyBool_FromLong = 88
    PyExc_Exception = 89
    PyExc_ValueError = 90
    PyErr_SetString = 91
    PyErr_NewException = 92
    PyInstanceMethod_New = 93
    PyCFunction_New = 94
    PyObject_Length = 95
    Py_GetPath = 96
    Py_GetPythonHome = 97
)